source 'http://rubygems.org'

gem 'rails', '4.2.4'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

platform :ruby do
  gem 'sqlite3'
end
platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
end

platform :ruby_19 do
  group :development, :test do
    gem 'debugger'
  end
end

platform :ruby_20, :ruby_21 do
  group :development, :test do
    gem 'pry'
  end
end

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

#gem "hobo_support", :path => "../.."
#gem "hobo_fields", :path => "../.."
#gem "dryml", :path => "../.."
gem "hobo", :path => "../.."
# gem "hobo_rapid", :path => "../.."
# gem "hobo_clean", :path => "../.."
# gem "hobo_clean_sidemenu", :path => "../.."
# gem "hobo_jquery", :path => "../.."
gem "hobo_jquery_ui", :path => "../.."

gem "jquery-ui-themes", "~> 0.0.4"

gem "hobo_bootstrap", :git => "git://github.com/Hobo/hobo_bootstrap"
gem "hobo_bootstrap_ui", :git => "git://github.com/Hobo/hobo_bootstrap_ui"
# gem "hobo_bootstrap", :path => "../../../hobo_bootstrap"
# gem "hobo_bootstrap_ui", :path => "../../../hobo_bootstrap_ui"

gem "hobo_will_paginate"#, :git => "git://github.com/Hobo/will_paginate.git"

gem "kramdown"
gem "RedCloth"

gem "shoulda", :group => :test
gem "factory_girl_rails", :group => :test

group :development, :test do
  gem 'capybara'#, :git => 'git://github.com/jnicklas/capybara.git'#, :ref => "83d8574c1d"  #"756ec1b2af70c66093c3b25976f520a3e6c3c2ae"
#  gem 'capybara-webkit', :git => 'git://github.com/thoughtbot/capybara-webkit.git'
#  gem 'capybara-webkit', :git => 'https://github.com/josephbridgwaterrowe/capybara-webkit.git', :branch => 'patch-1'
  gem 'database_cleaner'
  gem 'better_errors'
  gem "binding_of_caller"
  gem "capybara-screenshot"
  gem "poltergeist"
  gem 'phantomjs', :require => 'phantomjs/poltergeist'
end

gem "jquery-rails"

#gem "hobo-jquery", :git => "git://github.com/bryanlarsen/hobo-jquery.git", :branch => "no-prototype"

gem 'awesome_print'

gem "hobo_simple_color", :git => "git://github.com/Hobo/hobo_simple_color"
gem "hobo_tokeninput", :git => "git://github.com/Hobo/hobo_tokeninput"

# gem 'dryml-firemarker', :require => 'dryml13-firemarker', :group => :development, :path => '/work/dryml-firemarker'

# gem "quiet_assets"

gem 'acts_as_list'
gem 'paperclip', '3.5.2'
gem 'hobo_paperclip', :git => 'git://github.com/Hobo/hobo_paperclip'

gem "protected_attributes"
gem 'responders', '~> 2.0'

